networks:
  infra_minecraft:
    external: true

services:
  minecraft_server:
    build: ./
    image: minecraft-server
    container_name: minecraft-server-container
    restart: always
    networks:
      - infra_minecraft
    ports:
      - "4711:4711"
      - "25565:25565"
    volumes:
      - ./world:/root/Minecraft-Python/spidgot/world
      - ./world_nether:/root/Minecraft-Python/spidgot/world_nether
      - ./world_the_end:/root/Minecraft-Python/spidgot/world_the_end
      - ./logs:/root/Minecraft-Python/spidgot/logs
    deploy:
      resources:
        limits:
          cpus: '0.5'
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"